apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alpha

patchesStrategicMerge:
- deployment-patch.yaml

resources:
- ../../base
- cm-api-alpha.yaml
- ingress.yaml

images:
- name: 282966166539.dkr.ecr.ap-southeast-1.amazonaws.com/krida-bid-ui
  newTag: main-f4129f36-1646287390
