# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
      runs-on: ubuntu-latest
      name: Static Code Analysis
      steps:
        - uses: actions/checkout@v1
        - name: Semgrep
          id: semgrep
          uses: returntocorp/semgrep-action@v1
          with:
            config: p/react
  pushToECR:
    
    name: Push to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag Prefix
      id: tag
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: krida-bid-ui
      if: github.event_name == 'pull_request'
      run: |
          branch=${{ github.head_ref }}
          echo $branch
          branchName=${branch#refs/heads/}
          echo $branchName
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          tag=$(echo $branchName | cut -f2 -d'/')
          IMAGE_TAG="${tag}-${sha}-${ts}"
          image_url="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "image url is $image_url"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image_tag::$IMAGE_TAG"
      
    - name: Tag Prefix for main
      id: tag_main
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: krida-bid-ui
      if: github.event_name != 'pull_request'
      run: |
          echo ${GITHUB_REF}
          branchName=${GITHUB_REF#refs/heads/}
          echo $branchName
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          IMAGE_TAG="${branchName}-${sha}-${ts}"
          echo "::set-output name=BRANCH_NAME::${branchName}"
          echo "image tag is $IMAGE_TAG"
          image_url="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "image url is $image_url"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image_tag::$IMAGE_TAG"
      
    outputs:
      image_main_tag: ${{ steps.tag_main.outputs.image_tag }}
      image_tag: ${{ steps.tag.outputs.image_tag }}
      
  Deployment:
    needs: pushToECR
    name: Deployment steps
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set kustomize
      id: set_kustomize
      uses: imranismail/setup-kustomize@v1
    - name: set deployment
      id: set_deployment_main
      if: github.event_name != 'pull_request'
      run: |
        image_url=${{needs.pushToECR.outputs.image_main_tag}}
        echo $image_url
        cd deploy/overlays/alpha
        kustomize edit set image 282966166539.dkr.ecr.ap-southeast-1.amazonaws.com/krida-bid-ui:$image_url
    - name : edit deployment
      id: deployment_image_pr
      if: github.event_name == 'pull_request'
      run: |
        image_url=${{needs.pushToECR.outputs.image_tag}}
        echo $image_url
        cd deploy/overlays/dev
        kustomize edit set image 282966166539.dkr.ecr.ap-southeast-1.amazonaws.com/krida-bid-ui:$image_url
    - name: Commit changes
      uses: EndBug/add-and-commit@v7.5.0
      with:
        author_name: GitOps
        author_email: gitops@krida
        message: 'updated tag'
        branch: main
        add: '.'
        push: true
